# Generated by Django 4.1.4 on 2022-12-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('lang', models.CharField(choices=[('english', 'английский'), ('russian', 'русский'), ('kyrgyz', 'кыргызский')], max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'начинающий'), ('advanced', 'продвинутый'), ('professional', 'профи')], max_length=20)),
                ('image', models.ImageField(null=True, upload_to='courses')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.category')),
            ],
        ),
    ]
