# Generated by Django 4.1.4 on 2022-12-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='courses'),
        ),
    ]
